### PR TITLE
Robustify tls setup

### PR DESCRIPTION
**Pull request by rowanthorpe**
I've split these to three commits in case you want to cherrypick only one/some of them rather than merging all.

### CODE REVIEW

**Review by jdwx — APPROVED** [review]
Yup, good catch.  (On the $Help preset.)

**Review by jdwx — COMMENTED** [review]
Excess quoting is not necessary.  SH already treats variable substitution correctly except in (rare) cases where code is evaluated twice.

**Review by jdwx — COMMENTED** [review]
${1} is clearly correct and good from a consistency standpoint.  (${1}1 is always a possibility.)  ${#} isn't very pretty; I don't know how I feel about that.

**Comment by jdwx** [comment]
I will make the changes by hand and recommit since yours are based on the quoting change we didn't take.

**Comment by rowanthorpe** [comment]
As was the case for the other issues, I did the quoting for portable/POSIX scenario, but as you are only targeting FreeBSD system-shell which doesn't word-split by default, then true - it isn't needed.

BTW: if you don't want to use an entire pull-request you can either just `git cherry-pick` the commits you want rather than doing `git merge`, or just ask the pull-requester to `git rebase -i` to drop the commit on his/her branch (the changes automatically show up on the pull-request which you can then just `git merge` as usual)

**Pull request closed without merging**
