### PR TITLE
Fix "return" outside a function

### PR DESCRIPTION
**Pull request by rowanthorpe**
"return" should only return from a function or a sourced
script.

* in the best case that return might throw a warning
* in the worst case it would be silently ignored and execution
  would continue

### CODE REVIEW

**Review by jdwx — COMMENTED** [review]
From the sh man page:

"The syntax of the return command is

           return [exitstatus]

It terminates the current executional scope, returning from the closest nested function or sourced script; if no function or sourced script is being executed, it exits the shell instance."

**Comment by rowanthorpe** [comment]
Aside from style concerns (some people argue that `return` on non-sourced global scale can negatively affect grokability, but I am not that bothered personally) the actual functionality of this depends on how portable you want to be. I have a shell testing-ground setup here so I ran the following "return outside of function or sourced-script" test:

```sh
cat >test.sh <<EOF
return 0
EOF

for x in bash zsh dash fish busybox csh ksh mksh tcsh pdksh sash posh yash rc xonsh; do
  printf '%s: ' "$x"
  "$x" test.sh >/dev/null 2>&1 && printf 'OK\n' || printf 'failed\n'
done
```

with the following results:

```
bash: failed
zsh: OK
dash: OK
fish: failed
busybox: failed
csh: failed
ksh: OK
mksh: OK
tcsh: failed
pdksh: OK
sash: failed
posh: OK
yash: OK
rc: failed
xonsh: failed
```

Of course I know there are some obscure shells towards the end of that list (I didn't even include `rssh`, `rush`, or `lshell` because their security measures make iterating them in a script more difficult), but 8 failures out of 15 is a majority - and those failures include popular shells like `bash`, `csh`, `busybox`, and `fish`.

If you only want to target shell(s) which default to the strictly POSIX-compliant behaviour for this then this patch is not needed. Having said that, even running in bash in posix-mode (with `set -o posix`) still fails this test...

**Comment by jdwx** [comment]
The first line of this script is #!/bin/sh.  If you're running it in anything other than /bin/sh as shipped by FreeBSD, you're doing it wrong.

**Comment by rowanthorpe** [comment]
I am not so familiar with FreeBSD, but am used to various *nix platforms where the `/bin/sh` ultimately directs to the user's configured login-shell. *If* that is guaranteed to not even be allowed on FreeBSD(?), then it means you only need to target that shell, rather than worry about portability or POSIX-compliance.

Having said that - regarding POSIX-behaviour: I thought I'd remembered that the POSIX spec itself also forbade returning in global scope, but you made me doubt myself for a moment. I just found [in this blogpost](https://rgeissert.blogspot.gr/2013/03/a-bashism-week-returning.html) though that according to POSIX:2001 it is in fact forbidden. I am in a hurry so will not try and hunt down the authoritative doc at the moment, because if you are targeting only one shell it isn't necessary.

**Comment by jdwx** [comment]
Despite that this is supported, documented behavior of FreeBSD's sh, I looked up the actual Posix standard ( http://pubs.opengroup.org/onlinepubs/9699919799/ ) and it's less supportive:

"The return utility shall cause the shell to stop executing the current function or dot script. If the shell is not currently executing a function or dot script, the results are unspecified."

It goes on to discuss:

"The behavior of return when not in a function or dot script differs between the System V shell and the KornShell. In the System V shell this is an error, whereas in the KornShell, the effect is the same as exit."

**Pull request closed without merging**
